### PR TITLE
Merge pull request #2 from justmarkham/master

### PR DESCRIPTION
**Pull request by daresnick**
update2

### CODE REVIEW

**Comment by justmarkham** [comment]
@daresnick Hello! Is there something I can help you with?

**Comment by daresnick** [comment]
Sorry Kevin,
I was just trying to update my fork of your scikit-learn tips and got it backwards at first.


 
 
  On Wed, Apr 15, 2020 at 2:27 PM, Kevin Markham<notifications@github.com> wrote:   


@daresnick Hello! Is there something I can help you with?

**Comment by justmarkham** [comment]
@daresnick No problem! What you probably want to do is pull from my repository to your local machine, and then push to your fork. (Both of these operations are done locally, not via GitHub.)

This guide might be helpful to you: https://www.dataschool.io/simple-guide-to-forks-in-github-and-git/

**Comment by daresnick** [comment]
It was pretty easy to do from Github actually. I just got it backwards the second time I updated the fork.
Thanks for the link though.

 
 
  On Thu, Apr 16, 2020 at 11:10 AM, Kevin Markham<notifications@github.com> wrote:   


@daresnick No problem! What you probably want to do is pull from my repository to your local machine, and then push to your fork. (Both of these operations are done locally, not via GitHub.)

This guide might be helpful to you: https://www.dataschool.io/simple-guide-to-forks-in-github-and-git/

**Pull request closed without merging**
